name: Package Version
author: Simon Hengel
description: Determine the version of a Haskell package

branding:
  icon: package
  color: gray-dark

inputs:
  package-path:
    description: path to package
    required: true
    default: .

outputs:
  version: 
    description: package version
    value: ${{ steps.package-version.outputs.branch }}
  version-tags: 
    description: package version tags
    value: ${{ steps.package-version.outputs.tags }}

runs:
  using: composite
  steps:
    - shell: bash
      run: echo ":main ${{ inputs.path }}" | ghc --interactive -v0 ${{ github.action_path }}/src/PackageVersion.hs
      id: package-version
