name: Run Tests
author: Simon Hengel
description: Run all tests of a Haskell package

branding:
  icon: green
  color: check-square

inputs:
  package-path:
    default: .

  tag-prefix:
    default: v

  tag-pre-releases:
    default: false

  dry-run:
    default: false

outputs:
  created:
    value: ${{ steps.git-tag.outputs.created }}

  tag-name:
    value: ${{ steps.git-tag.outputs.tag-name }}

  version:
    value: ${{ steps.git-tag.outputs.version }}

  version-tags:
    value: ${{ steps.git-tag.outputs.version-tags }}

  version-with-tags:
    value: ${{ steps.git-tag.outputs.version-with-tags }}

runs:
  using: composite
  steps:
    - shell: bash

    - shell: bash
      run: cabal update

    - shell: bash
      run: cabal configure --enable-tests --enable-benchmarks # NOTE: --enable-tests is necessary due to https://github.com/haskell/cabal/issues/5079

    - shell: bash
      run: cabal build all

    - shell: bash
      run: cabal test all --test-show-details=direct
      env:
        HSPEC_OPTIONS: --color
