name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git tag v0.5.0
      - run: git push --tags && echo '::set-output name=created::true' || '::set-output name=created::false'
        id: create-tag

      - run: echo ">>> ${{ steps.create-tag.outputs.created }}"

      - if: steps.create-tag.outputs.created
        run: echo '>>> publish'
