name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo ":main" | ghc --interactive -v0 src/PackageVersion.hs
        id: package-version

      - run: git tag v0.5.0
      - run: git push --tags && echo '::set-output name=created::true' || echo 'exists'
        id: create-tag

      - run: echo ">>> ${{ steps.create-tag.outputs.created }}"

      - run: echo '>>> publish'
        if: steps.create-tag.outputs.created
