name: build

on:
  push:
    branches:
      - run-tests
  pull_request:
    branches:
      - run-tests

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sol/test-repo@run-tests
